name: ObsidianOptimizer
main: com.yourname.obsidianoptimizer.ObsidianOptimizerPlugin
version: 1.0.1
api-version: '1.20'
authors: [ 'you' ]
description: Adaptive per-player view distance & network load optimizer for Paper.
commands:
  oo:
    description: Obsidian Optimizer controls
    usage: /oo <status|reload|pause|resume|set [min|max|nt-min|nt-max] <value>>
permissions:
  obsidianoptimizer.admin:
    default: op
    description: Allows managing Obsidian Optimizer
